name: tom-sawyer
favicon: null
layout_spectrum: 0.55273
typography_spectrum: 0.898430711356923
title: Photo works
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#88725b'
    - '#f5f7f6'
    - '#62341a'
    - '#bebdc2'
  brandStrength: 0.3125
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
